target:
  protein: 1crn
  copy_struct: True # start with target conformation else fully extended
energyfn:
  name: EnvGrid
  grid_resolution: "3.0"
  hydrogens: false
movefn:
  name: NNOnly
  netconfig: config_aa10.yaml
  grid_resolution: "3.0"
  hydrogens: false
  res_char: X
  cpu: false
  stepwise: true  # move slowly to next value, else jump
  dstepfrac: 0.0001  # move dihedra len this fraction of difference to predicted
  flipMin: 0.9  # abs val of normalized +/-1 dihedral len must be greater to flip
  hstepfrac: 0.0001  # 0.1  # move hedra this fraction of difference to predicted
iterations: 10000

