process:
  train_fraction: 0.9
  epochs: 2000000
dataset:
  name: aa0
  path: ""
  res_char: X
  grid_resolution: 3.0
  learnXres: false
  hydrogens: false
  # restrict sample count for development, -1 for no limit
  limit: -1
  random_split: true
loader:
  batch_size: 256
  shuffle: true
  num_workers: 0
  pin_memory: true
model:
  name: resnet2layer
  devlist:
    - cuda:2
  layers: 7
loss:
  name: MSE
optimizer:
  name: SGD
  lr: 0.001
visualization:
  name: tensorboard
  path: runs
report:
  batch_freq: 100
checkpoint:
  path: /media/hd4t/hal/checkpoints
  epoch_freq: 1
  load_path: false
  # epoch to load checkpoint file from; -1 for no read, 'last' for highest number
  load: last
